### ISSUE TITLE
Memory update

### ISSUE THREAD

**Issue by TimQuester** [lab313ru/dsbxida#1]
The data in the Hex View IDA is not updated in debug mode.

Temporary solution: In the Doxbox-x debugger, configure the Data View to the desired memory segment (for example, Alt + D - DS). In this case, the DS segment in Hex View IDA will be updated. 

![изображение](https://user-images.githubusercontent.com/4231523/116239760-b4b48200-a76b-11eb-9f5a-9bc5ac54671d.png)
![изображение](https://user-images.githubusercontent.com/4231523/116239849-d1e95080-a76b-11eb-84ae-56c7bba8f2c7.png)

**Comment by TimQuester** [comment]
I was wrong, Data View in Dosbox-X does not affect the update of memory in IDA. It is not yet clear for what reason it is sometimes updated, and sometimes no. Forced update in IDA through "Refresh Memory" also does not give effect.

**Comment by lab313ru** [comment]
Fixed here: https://github.com/lab313ru/dsbxida/releases/tag/v1.1
