### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by WhiteMagicRaven** [lab313ru/dsbxida#2]
Please explain how to use that app.

**Comment by lab313ru** [comment]
Install files from ida7x folder to your IDA installation, so in result files from `ida7x\plugins` folder will appear in your IDA installation's `plugins` and files from `ida7x\loaders` folder will appear in your IDA installation's `loaders` folder.

After that open your MS-DOS binary in IDA. Then press F9 and choose the `dsbx debugger plugin` in the debuggers list. IDA will show you a dialog about waiting for Dosbox-X.

Then launch `dosbox-x.exe` from `dosbox_x_x64`/`dosbox_x_x86`, press menu `DOS`->`Quick launch executable...` and choose the same executable as has been opened in IDA. After that the debugger window will open.

**Comment by WhiteMagicRaven** [comment]
LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\dsbxida64.dll) error: Не найдена указанная процедура.
C:\Program Files\IDA Freeware 7.0\plugins\dsbxida64.dll: can't load file

LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\dsbxida64.dll) error: Не найдена указанная процедура.
C:\Program Files\IDA Freeware 7.0\plugins\dsbxida64.dll: can't load file

**Comment by lab313ru** [comment]
Plugin's archives contain ida75 and ida76 folders only, so it's not about ida 7.0.

Also, IDA 7.0 freeware doesn't support plugins, debuggers, etc.

**Comment by WhiteMagicRaven** [comment]
ah version mismatch ? i should have IDA 7.5 or IDA 7.6 right?

**Comment by lab313ru** [comment]
Exactly.

**Comment by WhiteMagicRaven** [comment]
Thanks, wiill try
